services:
#  oracle:
#    image: 'gvenzl/oracle-free:latest'
#    environment:
#      - 'ORACLE_PASSWORD=secret'
#    ports:
#      - '1521'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ugov-pj-timesheet'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=cnr'
    ports:
      - '5432'
