CREATE TABLE IF NOT EXISTS IE_PJ_MARCATURE_TIPI (
    ID_TIPO BIGINT PRIMARY KEY,
    CD_TIPO text,
    DS_TIPO text,
    CD_PROGETTO text,
    CD_UNITA_LAVORO text
);

INSERT INTO IE_PJ_MARCATURE_TIPI (id_tipo, cd_tipo) VALUES (1, 'F');
INSERT INTO IE_PJ_MARCATURE_TIPI (id_tipo, cd_tipo) VALUES (2, 'T');